apiVersion: v1
kind: Namespace
metadata:
  name: probotsharp
  labels:
    name: probotsharp
    app.kubernetes.io/name: probotsharp
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: probotsharp
  namespace: probotsharp
  labels:
    app: probotsharp
    app.kubernetes.io/name: probotsharp
automountServiceAccountToken: true
