apiVersion: v1
kind: Service
metadata:
  name: probotsharp
  namespace: probotsharp
  labels:
    app.kubernetes.io/name: probotsharp
    app.kubernetes.io/component: application
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: probotsharp
---
apiVersion: v1
kind: Service
metadata:
  name: probotsharp-headless
  namespace: probotsharp
  labels:
    app.kubernetes.io/name: probotsharp
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: probotsharp
